# reflex watch for any changes in any .go file "-r" match regex for \.go $$ is used to escape one $, --decoration==none remove any decoration, -s is for long running process and -- sh -c is for running certain command in shell
run:
	reflex -r '\.go$$' --decoration=none -s -- sh -c 'go run main.go'